version: 0.2
phases:
  pre_build:
    commands:
      - cd ./env/main/
  build:
    commands:
      - terraform --version
      - terraform init
      - terraform apply -target module.iam_policy --auto-approve
      - terraform apply -target module.iam_role -target module.k8s_karpenter -target module.iam_irsa --auto-approve
      - terraform apply --auto-approve