version: 0.2
phases:
  pre_build:
    commands:
      - cd ./env/main/
  build:
    commands:
      - terraform init
      #- terraform plan -target module.k8s_karpenter -target module.iam_policy -target module.iam_role
      - terraform plan
