namespace:
  name: test-app

service:
  name: test-app
  port: 8080

deployment:
  name: test-app
  replicas: 2
  image:
    repository: 672956273056.dkr.ecr.ap-northeast-2.amazonaws.com/ksj-apps
    tag: spring-8080-x64-v2
    pullPolicy: Always