apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-over-provioning
spec:
  # min / max count
  minReplicaCount: 1
  maxReplicaCount: 10

  # target
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx

  triggers:
    - type: cron
      metadata:
        timezone: Asia/Seoul
        start: 00 13 * * *
        end: 00 21 * * *
        desiredReplicas: "5"