apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: dev-private-node
spec:
  template:
    spec:
      kubelet:
        clusterDNS: ["10.100.0.10"]
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium","t3a.medium","t2.medium"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: dev-private-node
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    # WhenEmpty
    # consolidateAfter: 30s
    expireAfter: 1h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: dev-private-node
spec:
  amiFamily: AL2 # Amazon Linux 2
  userData: |
    #!/bin/bash
    Content-Type: multipart/mixed; boundary="//"
    MIME-Version: 1.0
    --//
    Content-Type: text/cloud-config; charset="us-ascii"
    MIME-Version: 1.0
    Content-Transfer-Encoding: 7bit
    Content-Disposition: attachment; filename="cloud-config.txt"
    #cloud-config
    cloud_final_modules:
    - [scripts-user, always]
    - [users-groups, always]
    users:
    - name : ec2-user
    groups : [ wheel ]
    shell : /bin/bash
    lock_passwd : false
    plain_text_passwd: 'admin0!'
    
    --//
    Content-Type: text/x-shellscript; charset="us-ascii"
    MIME-Version: 1.0
    Content-Transfer-Encoding: 7bit
    Content-Disposition: attachment; filename="userdata.txt"
    #!/bin/bash
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
  role: "dev_node_group_role" # replace with your karpenter node role
  subnetSelectorTerms:
    - tags:
        Name: "dev-private*"
  securityGroupSelectorTerms:
    - tags:
        Name: "eks-node-sg"
  amiSelectorTerms:
    - id: "ami-0c970162f407cdfd0"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 8Gi
        volumeType: gp3
        encrypted: true
  detailedMonitoring: false
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: dev-private-node-on-demand
spec:
  template:
    spec:
      kubelet:
        clusterDNS: ["10.100.0.10"]
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3a.small"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: dev-private-node-on-demand
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    # WhenEmpty
    # consolidateAfter: 30s
    expireAfter: 1h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: dev-private-node-on-demand
spec:
  amiFamily: AL2 # Amazon Linux 2
  userData: |
    #!/bin/bash
    Content-Type: multipart/mixed; boundary="//"
    MIME-Version: 1.0
    --//
    Content-Type: text/cloud-config; charset="us-ascii"
    MIME-Version: 1.0
    Content-Transfer-Encoding: 7bit
    Content-Disposition: attachment; filename="cloud-config.txt"
    #cloud-config
    cloud_final_modules:
    - [scripts-user, always]
    - [users-groups, always]
    users:
    - name : ec2-user
    groups : [ wheel ]
    shell : /bin/bash
    lock_passwd : false
    plain_text_passwd: 'admin0!'
    
    --//
    Content-Type: text/x-shellscript; charset="us-ascii"
    MIME-Version: 1.0
    Content-Transfer-Encoding: 7bit
    Content-Disposition: attachment; filename="userdata.txt"
    #!/bin/bash
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
  role: "dev_node_group_role" # replace with your karpenter node role
  subnetSelectorTerms:
    - tags:
        Name: "dev-private*"
  securityGroupSelectorTerms:
    - tags:
        Name: "eks-node-sg"
  amiSelectorTerms:
    - id: "ami-0c970162f407cdfd0"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 8Gi
        volumeType: gp3
        encrypted: true
  detailedMonitoring: false
