apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: test-sc


#mount pvc
#spec.containers.volumeMounts:
#  - mountPath: /data
#    name: test-volume
#volumes:
#  - name: test-volume
#    persistentVolumeClaim:
#      claimName: test-pvc