version: 0.2
phases:
  pre_build:
    commands:
      - pwd
      - ls -al
      - cd ./env/dev/
  build:
    commands:
      - terraform init
      - terraform plan -target module.k8s_karpenter
      - terraform plan -target module.iam_role
      - terraform plan -target module.iam_policy
