version: 0.2
phases:
  pre_build:
    commands:
      - pwd
      - ls -al
      - cd ./env/dev/
  build:
    commands:
      - terraform --version
      - terraform init
      - terraform apply -target module.k8s_karpenter -target module.iam_policy -target module.iam_role -target module.iam_irsa --auto-approve
      #- terraform apply -target module.subnets -target module.security_groups -target module.iam_policy -target module.iam_role --auto-approve
      #- terraform apply --auto-approve
