namespace:
  name: test-web

service:
  name: test-web
  port: 80

deployment:
  name: test-web
  replicas: 2
  image:
    repository: nginx
    tag: latest
    pullPolicy: Always

backend:
  name: test-app
  namespace: test-app

configmap:
  name: nginx-config
  config: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://test-app.test-app.svc.cluster.local:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
       } 
     }
    }


ingress:
  name: test-web
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: public-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet1, subnet2
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/group.name: shared-alb
    alb.ingress.kubernetes.io/success-codes: 200-302
